### ISSUE TITLE
npm run okta-hosted-login-server error

### ISSUE THREAD

**Issue by kcferguson1** [okta/samples-nodejs-express-4#53] opened 2018-09-21 15:42 UTC
getting error after running this command:  npm run okta-hosted-login-server

> @okta/samples-nodejs-express-4@3.0.0 okta-hosted-login-server C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master
> node okta-hosted-login/server.js

(node:26464) UnhandledPromiseRejectionWarning: RequestError: Request timed out
    at timeoutFn (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\got\index.js:319:53)
    at asPromise (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\got\index.js:397:18)
    at got (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\got\index.js:637:10)
    at Function.got.(anonymous function) [as get] (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\got\ind
ex.js:655:31)
    at Object.get (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\openid-client\lib\http.js:15:14)
    at Function.discover (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\openid-client\lib\issuer.js:195:
28)
    at Object.oidcUtil.createClient.context [as createClient] (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_mod
ules\@okta\oidc-middleware\src\oidcUtil.js:30:17)
    at new ExpressOIDC (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\node_modules\@okta\oidc-middleware\src\ExpressO
IDC.js:109:14)
    at new SampleWebServer (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\common\sample-web-server.js:30:16)
    at Object.<anonymous> (C:\Users\kcf\Desktop\Okta\Javascript\samples-nodejs-express-4-master\okta-hosted-login\server.js:19:1)
(node:26464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async func
tion without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handl
ed will terminate the Node.js process with a non-zero exit code.

**Comment by sn-donbenjamin** [comment] 2019-02-08 17:29
I got same error still have not figured it out

**Comment by hasanalkhaled** [comment] 2019-04-03 05:48
Hi, I'm having this same error. Can someone please assist?

**Comment by swiftone** [comment] 2019-04-17 21:17
I'm digging into the issue but have not been able to reproduce it - is anyone having this issue on a non-windows system?

**Comment by swiftone** [comment] 2019-05-01 21:06
Closing this as we cannot reproduce.  Please reopen if you continue have issues.

**Closed by swiftone** 2019-05-01 21:06 UTC
Labels: awaiting-response, cannot-reproduce
