### ISSUE TITLE
npm start /failed  with Resource temporarily unavailable

### ISSUE THREAD

**Issue by warddaniel** [okta/samples-nodejs-express-4#19] opened 2017-06-09 13:51 UTC
I am reporting this bug which throws an error but little else by way of error handling to detect root cause. 
```sh
 npm start

> @okta/samples-nodejs-express-4@1.0.0 prestart /home/trophy12/public_html/okta/samples/samples-nodejs-express-4
> build-frontend

node[1728]: pthread_create: Resource temporarily unavailable
child_process.js:524
    throw err;
    ^

Error: Command failed: DIST_OUT=/home/trophy12/public_html/okta/samples/samples-nodejs-express-4/dist npm run build
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at Object.<anonymous> (/home/trophy12/public_html/okta/samples/samples-nodejs-express-4/node_modules/@okta/samples-js-angular-1/scripts/build-frontend.js:23:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

npm ERR! Linux 2.6.32-042stab094.7
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @okta/samples-nodejs-express-4@1.0.0 prestart: `build-frontend`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @okta/samples-nodejs-express-4@1.0.0 prestart script 'build-frontend'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @okta/samples-nodejs-express-4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build-frontend
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @okta/samples-nodejs-express-4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @okta/samples-nodejs-express-4
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/trophy12/public_html/okta/samples/samples-nodejs-express-4/npm-debug.log


]# cat  /home/trophy12/public_html/okta/samples/samples-nodejs-express-4/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: @okta/samples-nodejs-express-4@1.0.0
6 verbose lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/trophy12/public_html/okta/samples/samples-nodejs-express-4/node_modules/.bin:/usr/local/jdk/bin:/home/trophy12/perl5/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/home/trophy12/bin
8 verbose lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: CWD: /home/trophy12/public_html/okta/samples/samples-nodejs-express-4
9 silly lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: Args: [ '-c', 'build-frontend' ]
10 silly lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle @okta/samples-nodejs-express-4@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: @okta/samples-nodejs-express-4@1.0.0 prestart: `build-frontend`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:891:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid @okta/samples-nodejs-express-4@1.0.0
14 verbose cwd /home/trophy12/public_html/okta/samples/samples-nodejs-express-4
15 error Linux 2.6.32-042stab094.7
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v6.11.0
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error @okta/samples-nodejs-express-4@1.0.0 prestart: `build-frontend`
20 error Exit status 1
21 error Failed at the @okta/samples-nodejs-express-4@1.0.0 prestart script 'build-frontend'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the @okta/samples-nodejs-express-4 package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     build-frontend
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs @okta/samples-nodejs-express-4
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls @okta/samples-nodejs-express-4
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by jmelberg-okta** [comment] 2017-06-26 23:46
@warddaniel: Looks like this issue is caused by the machine running out of address space. You can try: [Increasing number of threads per process in linux](https://stackoverflow.com/questions/344203/maximum-number-of-threads-per-process-in-linux)

**Comment by niketpathak** [comment] 2017-08-23 10:50
@jmelberg-okta What if increasing the number of threads in not an option (for example, in case of hosting on a shared server)? is there an alternate option?

**Comment by robertjd** [comment] 2018-07-10 15:32
Closing, as this was related to the old version of this sample.

**Closed by robertjd** 2018-07-10 15:32 UTC

**Comment by Sebastian-Nielsen** [comment] 2018-09-08 09:11
@niketpathak I am the same boat as you, did you solve it? If so, how?

**Comment by vthink123** [comment] 2018-09-17 07:32
I am also face same problem anybody got soluation?

node[849]: pthread_create: Resource temporarily unavailable

**Comment by robertjd** [comment] 2018-09-17 15:37
Hi @Sebastian-Nielsen , @vthink123 , could you tell me more about the environments that you're using, e.g. which OS, are you using docker, etc?  Thanks!

**Comment by Sebastian-Nielsen** [comment] 2018-09-17 16:30
> Hi @Sebastian-Nielsen , @vthink123 , could you tell me more about the environments that you're using, e.g. which OS, are you using docker, etc? Thanks!

@robertjd Windows 10, it's running on a heroku server. I found that it only occurs when I create too many requests/threads at once. If I run one at time everything works fine. So I guess the reason for the error is exactly as the error message phrase it: "resource temporarily unavailable" -> I got to slow down the work stress or optimize the code to run more efficiently.
